;; WebAssembly text format code generated by the drac compiler.

(module
 (import "drac" "printi" (func $printi (param i32)))
 (import "drac" "printc" (func $printc (param i32)))
 (import "drac" "prints" (func $prints (param i32)))
 (import "drac" "println" (func $println))
 (import "drac" "readi" (func $readi (result i32)))
 (import "drac" "reads" (func $reads (result i32)))
 (import "drac" "new" (func $new (param i32) (result i32)))
 (import "drac" "size" (func $size (param i32) (result i32)))
 (import "drac" "add" (func $add (param i32) (param i32) (result i32)))
 (import "drac" "get" (func $get (param i32) (param i32) (result i32)))
 (import "drac" "set" (func $set (param i32) (param i32) (param i32)))

	(func $print_array

		(param $a i32)
		(result i32)
		(local $_temp i32)
		(local $first i32)
		(local $i i32)
		(local $n i32)
		i32.const 1
		local.set $first
		i32.const 91
		call $printc
		i32.const 0
		local.set $i
		local.get $a
		call $size
		local.set $n
		block $00001
			loop $00002

				local.get $i
				local.get $n
				i32.lt_s

				i32.eqz
				br_if $00001

				local.get $first
				if
					i32.const 0
					local.set $first
				else
					i32.const 0
					call $new
					local.set $_temp
					local.get $_temp
					local.get $_temp
					i32.const 44
					call $add
					drop
					local.get $_temp
					i32.const 32
					call $add
					drop
					call $prints
				end
				local.get $a
				local.get $i
				call $get
				call $printi
				local.get $i
				i32.const 1
				i32.add
				local.set $i

				br $00002
			end
		end
		i32.const 93
		call $printc
		i32.const 0
		return
	)

	(func $sum_array

		(param $a i32)
		(result i32)
		(local $_temp i32)
		(local $sum i32)
		(local $i i32)
		(local $n i32)
		i32.const 0
		local.set $sum
		i32.const 0
		local.set $i
		local.get $a
		call $size
		local.set $n
		block $00003
			loop $00004

				local.get $i
				local.get $n
				i32.lt_s

				i32.eqz
				br_if $00003

				local.get $sum
				local.get $a
				local.get $i
				call $get
				i32.add
				local.set $sum
				local.get $i
				i32.const 1
				i32.add
				local.set $i

				br $00004
			end
		end
		local.get $sum
		return
		i32.const 0
		return
	)

	(func $max_array

		(param $a i32)
		(result i32)
		(local $_temp i32)
		(local $max i32)
		(local $i i32)
		(local $n i32)
		(local $x i32)
		local.get $a
		i32.const 0
		call $get
		local.set $max
		i32.const 0
		local.set $i
		local.get $a
		call $size
		local.set $n
		block $00005
			loop $00006

				local.get $i
				local.get $n
				i32.lt_s

				i32.eqz
				br_if $00005

				local.get $a
				local.get $i
				call $get
				local.set $x
				local.get $max
				local.get $x
				i32.lt_s
				if
					local.get $x
					local.set $max
				end
				local.get $i
				i32.const 1
				i32.add
				local.set $i

				br $00006
			end
		end
		local.get $max
		return
		i32.const 0
		return
	)

	(func $sort_array

		(param $a i32)
		(result i32)
		(local $_temp i32)
		(local $i i32)
		(local $j i32)
		(local $t i32)
		(local $n i32)
		(local $swap i32)
		local.get $a
		call $size
		local.set $n
		i32.const 0
		local.set $i
		block $00007
			loop $00008

				local.get $i
				local.get $n
				i32.const 1
				i32.sub
				i32.lt_s

				i32.eqz
				br_if $00007

				i32.const 0
				local.set $j
				i32.const 0
				local.set $swap
				block $00009
					loop $00010

						local.get $j
						local.get $n
						local.get $i
						i32.sub
						i32.const 1
						i32.sub
						i32.lt_s

						i32.eqz
						br_if $00009

						local.get $a
						local.get $j
						i32.const 1
						i32.add
						call $get
						local.get $a
						local.get $j
						call $get
						i32.lt_s
						if
							local.get $a
							local.get $j
							call $get
							local.set $t
							local.get $a
							local.get $j
							local.get $a
							local.get $j
							i32.const 1
							i32.add
							call $get
							call $set
							local.get $a
							local.get $j
							i32.const 1
							i32.add
							local.get $t
							call $set
							i32.const 1
							local.set $swap
						end
						local.get $j
						i32.const 1
						i32.add
						local.set $j

						br $00010
					end
				end
				local.get $swap
				i32.const 0
				i32.eq
				if
					br $00007
				end
				local.get $i
				i32.const 1
				i32.add
				local.set $i

				br $00008
			end
		end
		i32.const 0
		return
	)

	(func
		(export "main")

		(result i32)
		(local $_temp i32)
		(local $array i32)
		(local $sum i32)
		(local $max i32)
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 73
		call $add
		drop
		local.get $_temp
		i32.const 77
		call $add
		drop
		local.get $_temp
		i32.const 56
		call $add
		drop
		local.get $_temp
		i32.const 10
		call $add
		drop
		local.get $_temp
		i32.const 14
		call $add
		drop
		local.get $_temp
		i32.const 54
		call $add
		drop
		local.get $_temp
		i32.const 75
		call $add
		drop
		local.get $_temp
		i32.const 62
		call $add
		drop
		local.get $_temp
		i32.const 71
		call $add
		drop
		local.get $_temp
		i32.const 10
		call $add
		drop
		local.get $_temp
		i32.const 3
		call $add
		drop
		local.get $_temp
		i32.const 71
		call $add
		drop
		local.get $_temp
		i32.const 16
		call $add
		drop
		local.get $_temp
		i32.const 49
		call $add
		drop
		local.get $_temp
		i32.const 66
		call $add
		drop
		local.get $_temp
		i32.const 91
		call $add
		drop
		local.get $_temp
		i32.const 69
		call $add
		drop
		local.get $_temp
		i32.const 62
		call $add
		drop
		local.get $_temp
		i32.const 25
		call $add
		drop
		local.get $_temp
		i32.const 65
		call $add
		drop
		local.set $array
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 58
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		call $prints
		local.get $array
		call $print_array
		call $println
		local.get $array
		call $sum_array
		local.set $sum
		local.get $array
		call $max_array
		local.set $max
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 83
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 102
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 58
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		call $prints
		local.get $sum
		call $printi
		call $println
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 77
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 120
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 102
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 58
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		call $prints
		local.get $max
		call $printi
		call $println
		local.get $array
		call $sort_array
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 83
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 58
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		call $prints
		local.get $array
		call $print_array
		call $println
		i32.const 0
		return
	)
)
