;; WebAssembly text format code generated by the drac compiler.

(module
 (import "drac" "printi" (func $printi (param i32)))
 (import "drac" "printc" (func $printc (param i32)))
 (import "drac" "prints" (func $prints (param i32)))
 (import "drac" "println" (func $println))
 (import "drac" "readi" (func $readi (result i32)))
 (import "drac" "reads" (func $reads (result i32)))
 (import "drac" "new" (func $new (param i32) (result i32)))
 (import "drac" "size" (func $size (param i32) (result i32)))
 (import "drac" "add" (func $add (param i32) (param i32) (result i32)))
 (import "drac" "get" (func $get (param i32) (param i32) (result i32)))
 (import "drac" "set" (func $set (param i32) (param i32) (param i32)))
	(global $fails (mut i32) (i32.const 0))
	(global $asserts (mut i32) (i32.const 0))

	(func $assert

		(param $value1 i32)
		(param $value2 i32)
		(param $message i32)
		(result i32)
		(local $_temp i32)
		global.get $asserts
		i32.const 1
		i32.add
		global.set $asserts
		local.get $value1
		local.get $value2
		i32.eq
		i32.eqz
		if
			global.get $fails
			i32.const 1
			i32.add
			global.set $fails
			i32.const 0
			call $new
			local.set $_temp
			local.get $_temp
			local.get $_temp
			i32.const 65
			call $add
			drop
			local.get $_temp
			i32.const 115
			call $add
			drop
			local.get $_temp
			i32.const 115
			call $add
			drop
			local.get $_temp
			i32.const 101
			call $add
			drop
			local.get $_temp
			i32.const 114
			call $add
			drop
			local.get $_temp
			i32.const 116
			call $add
			drop
			local.get $_temp
			i32.const 105
			call $add
			drop
			local.get $_temp
			i32.const 111
			call $add
			drop
			local.get $_temp
			i32.const 110
			call $add
			drop
			local.get $_temp
			i32.const 32
			call $add
			drop
			local.get $_temp
			i32.const 102
			call $add
			drop
			local.get $_temp
			i32.const 97
			call $add
			drop
			local.get $_temp
			i32.const 105
			call $add
			drop
			local.get $_temp
			i32.const 108
			call $add
			drop
			local.get $_temp
			i32.const 117
			call $add
			drop
			local.get $_temp
			i32.const 114
			call $add
			drop
			local.get $_temp
			i32.const 101
			call $add
			drop
			local.get $_temp
			i32.const 58
			call $add
			drop
			local.get $_temp
			i32.const 32
			call $add
			drop
			call $prints
			local.get $message
			call $prints
			call $println
		end
		i32.const 0
		return
	)

	(func $some_fun

		(result i32)
		(local $_temp i32)
		i32.const 0
		return
	)

	(func $true_fun

		(result i32)
		(local $_temp i32)
		i32.const 1
		return
		i32.const 0
		return
	)

	(func $false_fun

		(result i32)
		(local $_temp i32)
		i32.const 0
		return
		i32.const 0
		return
	)

	(func $never_called

		(result i32)
		(local $_temp i32)
		i32.const 0
		i32.const 1
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 104
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		call $assert
		i32.const 0
		return
	)

	(func
		(export "main")

		(result i32)
		(local $_temp i32)
		i32.const 0
		global.set $fails
		i32.const 0
		global.set $asserts
		i32.const -0
		i32.const 0
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 49
		call $add
		drop
		call $assert
		i32.const -5
		i32.const 0
		i32.const 0
		i32.const 0
		i32.const 5
		i32.sub
		i32.sub
		i32.sub
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 50
		call $add
		drop
		call $assert
		i32.const 7
		i32.const 0
		i32.const 0
		i32.const 7
		i32.sub
		i32.sub
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 0
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		call $assert
		i32.const 5
		i32.const 5
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		call $assert
		i32.const 7
		i32.const 7
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 121
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 0
		i32.const 42
		i32.mul
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 42
		i32.const 7
		i32.const 6
		i32.mul
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 42
		i32.const -7
		i32.const -6
		i32.mul
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const -42
		i32.const -7
		i32.const 6
		i32.mul
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 112
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 1
		i32.const 2
		i32.div_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 118
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 6
		i32.const 20
		i32.const 3
		i32.div_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 118
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const -6
		i32.const -20
		i32.const 3
		i32.div_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 118
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 6
		i32.const -20
		i32.const -3
		i32.div_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 118
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 2
		i32.const 20
		i32.const 3
		i32.rem_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		call $assert
		i32.const -2
		i32.const -20
		i32.const 3
		i32.rem_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		call $assert
		i32.const -2
		i32.const -20
		i32.const -3
		i32.rem_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 109
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		call $assert
		i32.const 42
		i32.const 22
		i32.const 20
		i32.add
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 2
		i32.const 22
		i32.const -20
		i32.add
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const -42
		i32.const -22
		i32.const -20
		i32.add
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 42
		i32.const 80
		i32.const 38
		i32.sub
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 98
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const -118
		i32.const -80
		i32.const 38
		i32.sub
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 98
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const -42
		i32.const -80
		i32.const -38
		i32.sub
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 98
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 1
		i32.const 0
		i32.eq
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 84
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 0
		i32.const 0
		i32.eq
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 84
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 1
		i32.const 0
		i32.eq
		i32.const 0
		i32.eq
		i32.const 0
		i32.eq
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 84
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 0
		if(result i32)
			i32.const 0
			i32.eqz
			i32.eqz
		else
			i32.const 0
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 65
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 68
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 1
		if(result i32)
			i32.const 0
			i32.eqz
			i32.eqz
		else
			i32.const 0
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 65
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 68
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 0
		if(result i32)
			i32.const 1
			i32.eqz
			i32.eqz
		else
			i32.const 0
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 65
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 68
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 1
		if(result i32)
			i32.const 1
			i32.eqz
			i32.eqz
		else
			i32.const 0
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 65
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 68
		call $add
		drop
		call $assert
		i32.const 0
		call $false_fun
		if(result i32)
			call $never_called
			i32.eqz
			i32.eqz
		else
			i32.const 0
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 65
		call $add
		drop
		local.get $_temp
		i32.const 78
		call $add
		drop
		local.get $_temp
		i32.const 68
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 0
		if(result i32)
			i32.const 1
		else
			i32.const 0
			i32.eqz
			i32.eqz
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 82
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 1
		if(result i32)
			i32.const 1
		else
			i32.const 0
			i32.eqz
			i32.eqz
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 82
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 0
		if(result i32)
			i32.const 1
		else
			i32.const 1
			i32.eqz
			i32.eqz
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 82
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 1
		if(result i32)
			i32.const 1
		else
			i32.const 1
			i32.eqz
			i32.eqz
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 82
		call $add
		drop
		call $assert
		i32.const 1
		call $true_fun
		if(result i32)
			i32.const 1
		else
			call $never_called
			i32.eqz
			i32.eqz
		end
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 79
		call $add
		drop
		local.get $_temp
		i32.const 82
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 42
		i32.eq
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 42
		i32.const 43
		i32.eq
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 43
		i32.eq
		i32.eqz
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 42
		i32.const 42
		i32.eq
		i32.eqz
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 43
		i32.lt_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 104
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 42
		i32.const 42
		i32.lt_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 104
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 43
		i32.lt_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 104
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 42
		i32.const 42
		i32.lt_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 104
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 43
		i32.le_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 42
		i32.le_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 43
		i32.const 42
		i32.le_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 103
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 43
		i32.le_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		call $assert
		i32.const 1
		i32.const 42
		i32.const 42
		i32.le_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		call $assert
		i32.const 0
		i32.const 43
		i32.const 42
		i32.le_s
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 113
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		call $assert
		i32.const 0
		call $some_fun
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 102
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 99
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		call $assert
		global.get $fails
		call $printi
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 102
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 108
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 40
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 41
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 102
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 117
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 100
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 32
		call $add
		drop
		call $prints
		global.get $asserts
		call $printi
		i32.const 0
		call $new
		local.set $_temp
		local.get $_temp
		local.get $_temp
		i32.const 32
		call $add
		drop
		local.get $_temp
		i32.const 97
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 101
		call $add
		drop
		local.get $_temp
		i32.const 114
		call $add
		drop
		local.get $_temp
		i32.const 116
		call $add
		drop
		local.get $_temp
		i32.const 105
		call $add
		drop
		local.get $_temp
		i32.const 111
		call $add
		drop
		local.get $_temp
		i32.const 110
		call $add
		drop
		local.get $_temp
		i32.const 40
		call $add
		drop
		local.get $_temp
		i32.const 115
		call $add
		drop
		local.get $_temp
		i32.const 41
		call $add
		drop
		local.get $_temp
		i32.const 46
		call $add
		drop
		local.get $_temp
		i32.const 10
		call $add
		drop
		call $prints
		i32.const 0
		return
	)
)
